services:
  - type: web
    name: weedicider
    env: python
    buildCommand: pip install -r requirements.txt && cd dashboard-ui && npm ci && npm run build
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
