module.exports = function handler(req, res) {
  const scanId = req.query.scan_id || 'scan'
  const text = `WeedICider Scan Report\n\nScan ID: ${scanId}\nGenerated by WeedICider Vercel backend.\n`
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader('Content-Disposition', `attachment; filename="weedicider-report-${scanId}.pdf"`)
  res.statusCode = 200
  res.end(text)
}
